name: test_dbt
version: 1.0.0
config-version: 2
profile: test_dbt

model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
data-paths:
  - data
macro-paths:
  - macros
doc-paths:
  - docs
seed-paths:
  - seeds
snapshot-paths:
  - snapshots

clean-targets:
  - target
  - dbt_packages

models:
  test_dbt:
    +materialized: view
    staging:
      +materialized: table
