name: test_dbt
version: 1.0.1
config-version: 2
profile: test_dbt

model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
macro-paths:
  - macros
snapshot-paths:
  - snapshots

clean-targets:
  - target
  - dbt_packages

models:
  test_dbt:
    +materialized: view
    staging:
      +materialized: table
