jobs:
  - name: daily model runs
    targetName: dev
    schedule:
      type: cron
      entries: ["0 12 * * *"]
    timeout: 2h30m
    retryOnFailure: true
    steps:
      - name: run models
        command: dbt run
      - name: test models
        command: dbt test
